### ISSUE TITLE
Show Land Preview

### ISSUE THREAD

**Issue by bitoffdev** [Nitepone/terminally-tetris#22]
Currently, we have no grid lines or preview of where the currently falling block will land, which is an additional challenge for players. Many other implementations of Tetris have grid lines, a preview of where the block will land, or both.

The goal of this feature is add a preview of where the block will fall. Since our current separation of concerns places the responsibility of rendering the board on the Tetris library, the change should be made there.

**Comment by Nitepone** [comment]
Shadow blocks are now a part of the tetris library and are implemented in our client. Grid lines have not been added due to limitations with Ncurses.

Resolving this issue. Advise reconsidering gridlines in a future UI implementation if brought up during play testing.
